/**
 * Ключи фич подписочной модели для конструктора планов.
 * Каждый эндпоинт в микросервисах привязывается к одному ключу через RequireFeatureGuard.
 */
export enum SubscriptionFeature {
    // medicore_files
    FILES_UPLOAD = 'FILES_UPLOAD',
    FILES_LIST_DOWNLOAD = 'FILES_LIST_DOWNLOAD',

    // medicore_records
    RECORDS_PATIENTS = 'RECORDS_PATIENTS',
    RECORDS_EVENTS = 'RECORDS_EVENTS',
    RECORDS_DOCUMENTS = 'RECORDS_DOCUMENTS',
    RECORDS_APPOINTMENTS = 'RECORDS_APPOINTMENTS',
    RECORDS_MEDICATION_PRESCRIPTIONS = 'RECORDS_MEDICATION_PRESCRIPTIONS',
    RECORDS_MEDICATION_INTAKES = 'RECORDS_MEDICATION_INTAKES',
    RECORDS_LAB_TESTS = 'RECORDS_LAB_TESTS',
    RECORDS_IMAGING = 'RECORDS_IMAGING',
    RECORDS_HEALTH_TRACKERS = 'RECORDS_HEALTH_TRACKERS',
    RECORDS_SYMPTOMS = 'RECORDS_SYMPTOMS',
    RECORDS_ALLERGIES = 'RECORDS_ALLERGIES',
    RECORDS_VACCINATIONS = 'RECORDS_VACCINATIONS',
    RECORDS_DIAGNOSES = 'RECORDS_DIAGNOSES',
    RECORDS_TREATMENT_PLANS = 'RECORDS_TREATMENT_PLANS',
    RECORDS_CHRONIC_CONDITIONS = 'RECORDS_CHRONIC_CONDITIONS',
    RECORDS_SURGERIES = 'RECORDS_SURGERIES',
    RECORDS_MEDICINE_CABINET = 'RECORDS_MEDICINE_CABINET',
    RECORDS_FAMILY_ACCESS = 'RECORDS_FAMILY_ACCESS',
    RECORDS_STORAGE_USAGE = 'RECORDS_STORAGE_USAGE',

    // medicore_calendar
    CALENDAR_VIEW = 'CALENDAR_VIEW',
    CALENDAR_APPOINTMENTS = 'CALENDAR_APPOINTMENTS',
    CALENDAR_MEDICATION_SCHEDULES = 'CALENDAR_MEDICATION_SCHEDULES',
    CALENDAR_REMINDERS = 'CALENDAR_REMINDERS',

    // medicore_health
    HEALTH_ANALYTICS = 'HEALTH_ANALYTICS',
    HEALTH_SYMPTOMS = 'HEALTH_SYMPTOMS',

    // medicore_notification
    NOTIFICATIONS_READ = 'NOTIFICATIONS_READ',
    NOTIFICATIONS_PUSH = 'NOTIFICATIONS_PUSH',
    NOTIFICATIONS_EMAIL = 'NOTIFICATIONS_EMAIL',
    NOTIFICATIONS_SMS = 'NOTIFICATIONS_SMS',
    NOTIFICATIONS_TELEGRAM = 'NOTIFICATIONS_TELEGRAM',
    NOTIFICATIONS_TEMPLATES = 'NOTIFICATIONS_TEMPLATES',

    // medicore_profiles
    PROFILES_MAIN = 'PROFILES_MAIN',
    PROFILES_ADDRESSES = 'PROFILES_ADDRESSES',
    PROFILES_EMERGENCY_CONTACTS = 'PROFILES_EMERGENCY_CONTACTS',

    // medicore_reminders
    REMINDERS_FULL = 'REMINDERS_FULL',

    // medicore_support
    SUPPORT_TICKETS = 'SUPPORT_TICKETS',
}

export const SUBSCRIPTION_FEATURE_KEYS = Object.values(SubscriptionFeature) as string[];
